name: iOS-ipa-build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      # ✅ FIX HERE
      - name: Fix Podfile platform
        run: |
          echo "platform :ios, '13.0'" | cat - ios/Podfile > temp && mv temp ios/Podfile

      - run: cd ios && pod install --repo-update

      - run: flutter build ios --release --no-codesign

      - run: mkdir -p build/ios/iphoneos/Payload
      - run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          zip -r FlutterIpaExport.ipa Payload

      - name: Upload IPA
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS IPA build"
